### ISSUE TITLE
报错 Unexpected Application Error! Cannot destructure property 'localSetting' of 'd.state.user' as it is undefined.

### ISSUE THREAD

**Issue by Summa-rizer** [sixmillions/memos-replit#1]
@sixmillions大佬，你好！
昨天5月20日memos官方github已发布v0.13.0，大佬是否有时间编译更新一下。
我使用你的模板运行成功创建用户后，编写一条笔记出现如下报错：
Unexpected Application Error!
Cannot destructure property 'localSetting' of 'd.state.user' as it is undefined.
TypeError: Cannot destructure property 'localSetting' of 'd.state.user' as it is undefined.
at Cye (https://memos.****.repl.co/assets/index-85b15bcf.js:321:421)
at KM (https://memos.****.repl.co/assets/index-85b15bcf.js:83:19538)
at B7 (https://memos.****.repl.co/assets/index-85b15bcf.js:85:44055)
at w7 (https://memos.****.repl.co/assets/index-85b15bcf.js:85:39787)
at MK (https://memos.****.repl.co/assets/index-85b15bcf.js:85:39715)
at RT (https://memos.****.repl.co/assets/index-85b15bcf.js:85:39568)
at cA (https://memos.****.repl.co/assets/index-85b15bcf.js:85:35933)
at M7 (https://memos.****.repl.co/assets/index-85b15bcf.js:85:34882)
at C (https://memos.****.repl.co/assets/index-85b15bcf.js:70:1577)
at MessagePort.z (https://memos.****.repl.co/assets/index-85b15bcf.js:70:1942)

**Comment by sixmillions** [comment]
你好，v0.12.2匿名访问是有这个问题。
如果你先访问 /auth 路径，登录后，就没这个问题了
v0.13.0 版本已经修复

**Comment by sixmillions** [comment]
# v0.13.0发布

**备份数据后**，尝试升级

> https://replit.com/@sixmillions/memos-replit
